### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mathialakan** [Bhattacharya-Lab/SPECS#2]
It gives segmentation fault, I went through the code it fails on loading pdbs, specifically while reading the line.
Could you verify it?
I used gcc 9.3.

**Comment by Bhattacharya-Lab** [comment]
Is recommended to download the SPECS source code and compile it on your machine, which may resolve the issue. Alternatively, you are welcome to try SPECS out online server at http://watson.cse.eng.auburn.edu/SPECS/.
